// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: metric_ingest_stats.proto

package chqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricIngestStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HllSketch     []byte                 `protobuf:"bytes,1,opt,name=hllSketch,proto3" json:"hllSketch,omitempty"`
	Key           *MetricIngestStat_Key  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricIngestStat) Reset() {
	*x = MetricIngestStat{}
	mi := &file_metric_ingest_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricIngestStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricIngestStat) ProtoMessage() {}

func (x *MetricIngestStat) ProtoReflect() protoreflect.Message {
	mi := &file_metric_ingest_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricIngestStat.ProtoReflect.Descriptor instead.
func (*MetricIngestStat) Descriptor() ([]byte, []int) {
	return file_metric_ingest_stats_proto_rawDescGZIP(), []int{0}
}

func (x *MetricIngestStat) GetHllSketch() []byte {
	if x != nil {
		return x.HllSketch
	}
	return nil
}

func (x *MetricIngestStat) GetKey() *MetricIngestStat_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type MetricIngestStatsList struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Stats         []*MetricIngestStat                     `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	Key           *MetricIngestStatsList_Key              `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Exemplars     []*MetricIngestStatsList_MetricExemplar `protobuf:"bytes,3,rep,name=exemplars,proto3" json:"exemplars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricIngestStatsList) Reset() {
	*x = MetricIngestStatsList{}
	mi := &file_metric_ingest_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricIngestStatsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricIngestStatsList) ProtoMessage() {}

func (x *MetricIngestStatsList) ProtoReflect() protoreflect.Message {
	mi := &file_metric_ingest_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricIngestStatsList.ProtoReflect.Descriptor instead.
func (*MetricIngestStatsList) Descriptor() ([]byte, []int) {
	return file_metric_ingest_stats_proto_rawDescGZIP(), []int{1}
}

func (x *MetricIngestStatsList) GetStats() []*MetricIngestStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *MetricIngestStatsList) GetKey() *MetricIngestStatsList_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MetricIngestStatsList) GetExemplars() []*MetricIngestStatsList_MetricExemplar {
	if x != nil {
		return x.Exemplars
	}
	return nil
}

type MetricIngestStat_Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metricName,proto3" json:"metricName,omitempty"`
	TagName       string                 `protobuf:"bytes,3,opt,name=tagName,proto3" json:"tagName,omitempty"`
	TsHour        int64                  `protobuf:"varint,4,opt,name=tsHour,proto3" json:"tsHour,omitempty"`
	CustomerId    string                 `protobuf:"bytes,5,opt,name=customerId,proto3" json:"customerId,omitempty"`
	PhaseType     string                 `protobuf:"bytes,6,opt,name=phaseType,proto3" json:"phaseType,omitempty"`
	ProcessorId   string                 `protobuf:"bytes,7,opt,name=processorId,proto3" json:"processorId,omitempty"`
	CollectorId   string                 `protobuf:"bytes,8,opt,name=collectorId,proto3" json:"collectorId,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty"`
	TagScope      string                 `protobuf:"bytes,10,opt,name=tagScope,proto3" json:"tagScope,omitempty"`
	MetricType    string                 `protobuf:"bytes,11,opt,name=metricType,proto3" json:"metricType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricIngestStat_Key) Reset() {
	*x = MetricIngestStat_Key{}
	mi := &file_metric_ingest_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricIngestStat_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricIngestStat_Key) ProtoMessage() {}

func (x *MetricIngestStat_Key) ProtoReflect() protoreflect.Message {
	mi := &file_metric_ingest_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricIngestStat_Key.ProtoReflect.Descriptor instead.
func (*MetricIngestStat_Key) Descriptor() ([]byte, []int) {
	return file_metric_ingest_stats_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MetricIngestStat_Key) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *MetricIngestStat_Key) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricIngestStat_Key) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *MetricIngestStat_Key) GetTsHour() int64 {
	if x != nil {
		return x.TsHour
	}
	return 0
}

func (x *MetricIngestStat_Key) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MetricIngestStat_Key) GetPhaseType() string {
	if x != nil {
		return x.PhaseType
	}
	return ""
}

func (x *MetricIngestStat_Key) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *MetricIngestStat_Key) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *MetricIngestStat_Key) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *MetricIngestStat_Key) GetTagScope() string {
	if x != nil {
		return x.TagScope
	}
	return ""
}

func (x *MetricIngestStat_Key) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

type MetricIngestStatsList_Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	PhaseType     string                 `protobuf:"bytes,2,opt,name=phaseType,proto3" json:"phaseType,omitempty"`
	TsHour        int64                  `protobuf:"varint,3,opt,name=tsHour,proto3" json:"tsHour,omitempty"`
	VendorId      string                 `protobuf:"bytes,4,opt,name=vendorId,proto3" json:"vendorId,omitempty"`
	CollectorId   string                 `protobuf:"bytes,5,opt,name=collectorId,proto3" json:"collectorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricIngestStatsList_Key) Reset() {
	*x = MetricIngestStatsList_Key{}
	mi := &file_metric_ingest_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricIngestStatsList_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricIngestStatsList_Key) ProtoMessage() {}

func (x *MetricIngestStatsList_Key) ProtoReflect() protoreflect.Message {
	mi := &file_metric_ingest_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricIngestStatsList_Key.ProtoReflect.Descriptor instead.
func (*MetricIngestStatsList_Key) Descriptor() ([]byte, []int) {
	return file_metric_ingest_stats_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MetricIngestStatsList_Key) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MetricIngestStatsList_Key) GetPhaseType() string {
	if x != nil {
		return x.PhaseType
	}
	return ""
}

func (x *MetricIngestStatsList_Key) GetTsHour() int64 {
	if x != nil {
		return x.TsHour
	}
	return 0
}

func (x *MetricIngestStatsList_Key) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *MetricIngestStatsList_Key) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type MetricIngestStatsList_MetricExemplar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metricName,proto3" json:"metricName,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	MetricType    string                 `protobuf:"bytes,3,opt,name=metricType,proto3" json:"metricType,omitempty"`
	Exemplar      []byte                 `protobuf:"bytes,4,opt,name=exemplar,proto3" json:"exemplar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricIngestStatsList_MetricExemplar) Reset() {
	*x = MetricIngestStatsList_MetricExemplar{}
	mi := &file_metric_ingest_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricIngestStatsList_MetricExemplar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricIngestStatsList_MetricExemplar) ProtoMessage() {}

func (x *MetricIngestStatsList_MetricExemplar) ProtoReflect() protoreflect.Message {
	mi := &file_metric_ingest_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricIngestStatsList_MetricExemplar.ProtoReflect.Descriptor instead.
func (*MetricIngestStatsList_MetricExemplar) Descriptor() ([]byte, []int) {
	return file_metric_ingest_stats_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MetricIngestStatsList_MetricExemplar) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricIngestStatsList_MetricExemplar) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MetricIngestStatsList_MetricExemplar) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *MetricIngestStatsList_MetricExemplar) GetExemplar() []byte {
	if x != nil {
		return x.Exemplar
	}
	return nil
}

var File_metric_ingest_stats_proto protoreflect.FileDescriptor

const file_metric_ingest_stats_proto_rawDesc = "" +
	"\n" +
	"\x19metric_ingest_stats.proto\x12\x05chqpb\x1a\x0fattribute.proto\"\xc3\x03\n" +
	"\x10MetricIngestStat\x12\x1c\n" +
	"\thllSketch\x18\x01 \x01(\fR\thllSketch\x12-\n" +
	"\x03key\x18\x02 \x01(\v2\x1b.chqpb.MetricIngestStat.KeyR\x03key\x1a\xe1\x02\n" +
	"\x03Key\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1e\n" +
	"\n" +
	"metricName\x18\x02 \x01(\tR\n" +
	"metricName\x12\x18\n" +
	"\atagName\x18\x03 \x01(\tR\atagName\x12\x16\n" +
	"\x06tsHour\x18\x04 \x01(\x03R\x06tsHour\x12\x1e\n" +
	"\n" +
	"customerId\x18\x05 \x01(\tR\n" +
	"customerId\x12\x1c\n" +
	"\tphaseType\x18\x06 \x01(\tR\tphaseType\x12 \n" +
	"\vprocessorId\x18\a \x01(\tR\vprocessorId\x12 \n" +
	"\vcollectorId\x18\b \x01(\tR\vcollectorId\x120\n" +
	"\n" +
	"attributes\x18\t \x03(\v2\x10.chqpb.AttributeR\n" +
	"attributes\x12\x1a\n" +
	"\btagScope\x18\n" +
	" \x01(\tR\btagScope\x12\x1e\n" +
	"\n" +
	"metricType\x18\v \x01(\tR\n" +
	"metricType\"\xf2\x03\n" +
	"\x15MetricIngestStatsList\x12-\n" +
	"\x05stats\x18\x01 \x03(\v2\x17.chqpb.MetricIngestStatR\x05stats\x122\n" +
	"\x03key\x18\x02 \x01(\v2 .chqpb.MetricIngestStatsList.KeyR\x03key\x12I\n" +
	"\texemplars\x18\x03 \x03(\v2+.chqpb.MetricIngestStatsList.MetricExemplarR\texemplars\x1a\x99\x01\n" +
	"\x03Key\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1c\n" +
	"\tphaseType\x18\x02 \x01(\tR\tphaseType\x12\x16\n" +
	"\x06tsHour\x18\x03 \x01(\x03R\x06tsHour\x12\x1a\n" +
	"\bvendorId\x18\x04 \x01(\tR\bvendorId\x12 \n" +
	"\vcollectorId\x18\x05 \x01(\tR\vcollectorId\x1a\x8e\x01\n" +
	"\x0eMetricExemplar\x12\x1e\n" +
	"\n" +
	"metricName\x18\x01 \x01(\tR\n" +
	"metricName\x12 \n" +
	"\vserviceName\x18\x02 \x01(\tR\vserviceName\x12\x1e\n" +
	"\n" +
	"metricType\x18\x03 \x01(\tR\n" +
	"metricType\x12\x1a\n" +
	"\bexemplar\x18\x04 \x01(\fR\bexemplarB\tZ\a.;chqpbb\x06proto3"

var (
	file_metric_ingest_stats_proto_rawDescOnce sync.Once
	file_metric_ingest_stats_proto_rawDescData []byte
)

func file_metric_ingest_stats_proto_rawDescGZIP() []byte {
	file_metric_ingest_stats_proto_rawDescOnce.Do(func() {
		file_metric_ingest_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_ingest_stats_proto_rawDesc), len(file_metric_ingest_stats_proto_rawDesc)))
	})
	return file_metric_ingest_stats_proto_rawDescData
}

var file_metric_ingest_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metric_ingest_stats_proto_goTypes = []any{
	(*MetricIngestStat)(nil),                     // 0: chqpb.MetricIngestStat
	(*MetricIngestStatsList)(nil),                // 1: chqpb.MetricIngestStatsList
	(*MetricIngestStat_Key)(nil),                 // 2: chqpb.MetricIngestStat.Key
	(*MetricIngestStatsList_Key)(nil),            // 3: chqpb.MetricIngestStatsList.Key
	(*MetricIngestStatsList_MetricExemplar)(nil), // 4: chqpb.MetricIngestStatsList.MetricExemplar
	(*Attribute)(nil),                            // 5: chqpb.Attribute
}
var file_metric_ingest_stats_proto_depIdxs = []int32{
	2, // 0: chqpb.MetricIngestStat.key:type_name -> chqpb.MetricIngestStat.Key
	0, // 1: chqpb.MetricIngestStatsList.stats:type_name -> chqpb.MetricIngestStat
	3, // 2: chqpb.MetricIngestStatsList.key:type_name -> chqpb.MetricIngestStatsList.Key
	4, // 3: chqpb.MetricIngestStatsList.exemplars:type_name -> chqpb.MetricIngestStatsList.MetricExemplar
	5, // 4: chqpb.MetricIngestStat.Key.attributes:type_name -> chqpb.Attribute
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_metric_ingest_stats_proto_init() }
func file_metric_ingest_stats_proto_init() {
	if File_metric_ingest_stats_proto != nil {
		return
	}
	file_attribute_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_ingest_stats_proto_rawDesc), len(file_metric_ingest_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metric_ingest_stats_proto_goTypes,
		DependencyIndexes: file_metric_ingest_stats_proto_depIdxs,
		MessageInfos:      file_metric_ingest_stats_proto_msgTypes,
	}.Build()
	File_metric_ingest_stats_proto = out.File
	file_metric_ingest_stats_proto_goTypes = nil
	file_metric_ingest_stats_proto_depIdxs = nil
}
