// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: resource_entity.proto

package chqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceEntityProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Edges         []*ResourceEdge        `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEntityProto) Reset() {
	*x = ResourceEntityProto{}
	mi := &file_resource_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEntityProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEntityProto) ProtoMessage() {}

func (x *ResourceEntityProto) ProtoReflect() protoreflect.Message {
	mi := &file_resource_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEntityProto.ProtoReflect.Descriptor instead.
func (*ResourceEntityProto) Descriptor() ([]byte, []int) {
	return file_resource_entity_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceEntityProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceEntityProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceEntityProto) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ResourceEntityProto) GetEdges() []*ResourceEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type ResourceEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Extra         string                 `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEdge) Reset() {
	*x = ResourceEdge{}
	mi := &file_resource_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEdge) ProtoMessage() {}

func (x *ResourceEdge) ProtoReflect() protoreflect.Message {
	mi := &file_resource_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEdge.ProtoReflect.Descriptor instead.
func (*ResourceEdge) Descriptor() ([]byte, []int) {
	return file_resource_entity_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceEdge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceEdge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceEdge) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResourceEdge) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type ResourceEntityProtoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      [][]byte               `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      [][]byte               `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEntityProtoList) Reset() {
	*x = ResourceEntityProtoList{}
	mi := &file_resource_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEntityProtoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEntityProtoList) ProtoMessage() {}

func (x *ResourceEntityProtoList) ProtoReflect() protoreflect.Message {
	mi := &file_resource_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEntityProtoList.ProtoReflect.Descriptor instead.
func (*ResourceEntityProtoList) Descriptor() ([]byte, []int) {
	return file_resource_entity_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceEntityProtoList) GetEntities() [][]byte {
	if x != nil {
		return x.Entities
	}
	return nil
}

var File_resource_entity_proto protoreflect.FileDescriptor

var file_resource_entity_proto_rawDesc = string([]byte{
var file_resource_entity_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x68, 0x71, 0x70, 0x62, 0x22, 0xf3,
	0x01, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4a,
	0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x68, 0x71, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x64,
	0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x68, 0x71, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x64, 0x67, 0x65, 0x52, 0x05,
	0x65, 0x64, 0x67, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x62, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x45, 0x64, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x35, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x63, 0x68, 0x71, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_resource_entity_proto_rawDescOnce sync.Once
	file_resource_entity_proto_rawDescData []byte
	file_resource_entity_proto_rawDescData []byte
)

func file_resource_entity_proto_rawDescGZIP() []byte {
	file_resource_entity_proto_rawDescOnce.Do(func() {
		file_resource_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_entity_proto_rawDesc), len(file_resource_entity_proto_rawDesc)))
		file_resource_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_entity_proto_rawDesc), len(file_resource_entity_proto_rawDesc)))
	})
	return file_resource_entity_proto_rawDescData
}

var file_resource_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resource_entity_proto_goTypes = []any{
	(*ResourceEntityProto)(nil),     // 0: chqpb.ResourceEntityProto
	(*ResourceEdge)(nil),            // 1: chqpb.ResourceEdge
	(*ResourceEntityProtoList)(nil), // 2: chqpb.ResourceEntityProtoList
	nil,                             // 3: chqpb.ResourceEntityProto.AttributesEntry
}
var file_resource_entity_proto_depIdxs = []int32{
	3, // 0: chqpb.ResourceEntityProto.attributes:type_name -> chqpb.ResourceEntityProto.AttributesEntry
	1, // 1: chqpb.ResourceEntityProto.edges:type_name -> chqpb.ResourceEdge
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resource_entity_proto_init() }
func file_resource_entity_proto_init() {
	if File_resource_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_entity_proto_rawDesc), len(file_resource_entity_proto_rawDesc)),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_entity_proto_rawDesc), len(file_resource_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_entity_proto_goTypes,
		DependencyIndexes: file_resource_entity_proto_depIdxs,
		MessageInfos:      file_resource_entity_proto_msgTypes,
	}.Build()
	File_resource_entity_proto = out.File
	file_resource_entity_proto_goTypes = nil
	file_resource_entity_proto_depIdxs = nil
}
