// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: resource_entity.proto

package chqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ResourceEntityId      `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Relationship  string                 `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Source        *ResourceEntityId      `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeProto) Reset() {
	*x = EdgeProto{}
	mi := &file_resource_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeProto) ProtoMessage() {}

func (x *EdgeProto) ProtoReflect() protoreflect.Message {
	mi := &file_resource_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeProto.ProtoReflect.Descriptor instead.
func (*EdgeProto) Descriptor() ([]byte, []int) {
	return file_resource_entity_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeProto) GetTarget() *ResourceEntityId {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EdgeProto) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *EdgeProto) GetSource() *ResourceEntityId {
	if x != nil {
		return x.Source
	}
	return nil
}

type ResourceEntityProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *ResourceEntityId      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Edges         []*EdgeProto           `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEntityProto) Reset() {
	*x = ResourceEntityProto{}
	mi := &file_resource_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEntityProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEntityProto) ProtoMessage() {}

func (x *ResourceEntityProto) ProtoReflect() protoreflect.Message {
	mi := &file_resource_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEntityProto.ProtoReflect.Descriptor instead.
func (*ResourceEntityProto) Descriptor() ([]byte, []int) {
	return file_resource_entity_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceEntityProto) GetId() *ResourceEntityId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ResourceEntityProto) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ResourceEntityProto) GetEdges() []*EdgeProto {
	if x != nil {
		return x.Edges
	}
	return nil
}

type ResourceEntityProtoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      [][]byte               `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceEntityProtoList) Reset() {
	*x = ResourceEntityProtoList{}
	mi := &file_resource_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEntityProtoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEntityProtoList) ProtoMessage() {}

func (x *ResourceEntityProtoList) ProtoReflect() protoreflect.Message {
	mi := &file_resource_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEntityProtoList.ProtoReflect.Descriptor instead.
func (*ResourceEntityProtoList) Descriptor() ([]byte, []int) {
	return file_resource_entity_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceEntityProtoList) GetEntities() [][]byte {
	if x != nil {
		return x.Entities
	}
	return nil
}

var File_resource_entity_proto protoreflect.FileDescriptor

const file_resource_entity_proto_rawDesc = "" +
	"\n" +
	"\x15resource_entity.proto\x12\x05chqpb\x1a\x18resource_entity_id.proto\"\x91\x01\n" +
	"\tEdgeProto\x12/\n" +
	"\x06target\x18\x01 \x01(\v2\x17.chqpb.ResourceEntityIdR\x06target\x12\"\n" +
	"\frelationship\x18\x02 \x01(\tR\frelationship\x12/\n" +
	"\x06source\x18\x03 \x01(\v2\x17.chqpb.ResourceEntityIdR\x06source\"\xf1\x01\n" +
	"\x13ResourceEntityProto\x12'\n" +
	"\x02id\x18\x01 \x01(\v2\x17.chqpb.ResourceEntityIdR\x02id\x12J\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2*.chqpb.ResourceEntityProto.AttributesEntryR\n" +
	"attributes\x12&\n" +
	"\x05edges\x18\x03 \x03(\v2\x10.chqpb.EdgeProtoR\x05edges\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x17ResourceEntityProtoList\x12\x1a\n" +
	"\bentities\x18\x01 \x03(\fR\bentitiesB\tZ\a.;chqpbb\x06proto3"

var (
	file_resource_entity_proto_rawDescOnce sync.Once
	file_resource_entity_proto_rawDescData []byte
)

func file_resource_entity_proto_rawDescGZIP() []byte {
	file_resource_entity_proto_rawDescOnce.Do(func() {
		file_resource_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_entity_proto_rawDesc), len(file_resource_entity_proto_rawDesc)))
	})
	return file_resource_entity_proto_rawDescData
}

var file_resource_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resource_entity_proto_goTypes = []any{
	(*EdgeProto)(nil),               // 0: chqpb.EdgeProto
	(*ResourceEntityProto)(nil),     // 1: chqpb.ResourceEntityProto
	(*ResourceEntityProtoList)(nil), // 2: chqpb.ResourceEntityProtoList
	nil,                             // 3: chqpb.ResourceEntityProto.AttributesEntry
	(*ResourceEntityId)(nil),        // 4: chqpb.ResourceEntityId
}
var file_resource_entity_proto_depIdxs = []int32{
	4, // 0: chqpb.EdgeProto.target:type_name -> chqpb.ResourceEntityId
	4, // 1: chqpb.EdgeProto.source:type_name -> chqpb.ResourceEntityId
	4, // 2: chqpb.ResourceEntityProto.id:type_name -> chqpb.ResourceEntityId
	3, // 3: chqpb.ResourceEntityProto.attributes:type_name -> chqpb.ResourceEntityProto.AttributesEntry
	0, // 4: chqpb.ResourceEntityProto.edges:type_name -> chqpb.EdgeProto
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_resource_entity_proto_init() }
func file_resource_entity_proto_init() {
	if File_resource_entity_proto != nil {
		return
	}
	file_resource_entity_id_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_entity_proto_rawDesc), len(file_resource_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_entity_proto_goTypes,
		DependencyIndexes: file_resource_entity_proto_depIdxs,
		MessageInfos:      file_resource_entity_proto_msgTypes,
	}.Build()
	File_resource_entity_proto = out.File
	file_resource_entity_proto_goTypes = nil
	file_resource_entity_proto_depIdxs = nil
}
