// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: resource_entity_id.proto

package chqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeTuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AttributeTuple) Reset() {
	*x = AttributeTuple{}
	mi := &file_resource_entity_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeTuple) ProtoMessage() {}

func (x *AttributeTuple) ProtoReflect() protoreflect.Message {
	mi := &file_resource_entity_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeTuple.ProtoReflect.Descriptor instead.
func (*AttributeTuple) Descriptor() ([]byte, []int) {
	return file_resource_entity_id_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeTuple) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributeTuple) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ResourceEntityId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash            string            `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Name            string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type            string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AttributeTuples []*AttributeTuple `protobuf:"bytes,4,rep,name=attributeTuples,proto3" json:"attributeTuples,omitempty"`
}

func (x *ResourceEntityId) Reset() {
	*x = ResourceEntityId{}
	mi := &file_resource_entity_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEntityId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEntityId) ProtoMessage() {}

func (x *ResourceEntityId) ProtoReflect() protoreflect.Message {
	mi := &file_resource_entity_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEntityId.ProtoReflect.Descriptor instead.
func (*ResourceEntityId) Descriptor() ([]byte, []int) {
	return file_resource_entity_id_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceEntityId) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ResourceEntityId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceEntityId) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceEntityId) GetAttributeTuples() []*AttributeTuple {
	if x != nil {
		return x.AttributeTuples
	}
	return nil
}

var File_resource_entity_id_proto protoreflect.FileDescriptor

var file_resource_entity_id_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x68, 0x71, 0x70,
	0x62, 0x22, 0x38, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x75,
	0x70, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x10,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x0f,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x68, 0x71, 0x70, 0x62, 0x2e, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x0f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x63, 0x68, 0x71, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_entity_id_proto_rawDescOnce sync.Once
	file_resource_entity_id_proto_rawDescData = file_resource_entity_id_proto_rawDesc
)

func file_resource_entity_id_proto_rawDescGZIP() []byte {
	file_resource_entity_id_proto_rawDescOnce.Do(func() {
		file_resource_entity_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_entity_id_proto_rawDescData)
	})
	return file_resource_entity_id_proto_rawDescData
}

var file_resource_entity_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_entity_id_proto_goTypes = []any{
	(*AttributeTuple)(nil),   // 0: chqpb.AttributeTuple
	(*ResourceEntityId)(nil), // 1: chqpb.ResourceEntityId
}
var file_resource_entity_id_proto_depIdxs = []int32{
	0, // 0: chqpb.ResourceEntityId.attributeTuples:type_name -> chqpb.AttributeTuple
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resource_entity_id_proto_init() }
func file_resource_entity_id_proto_init() {
	if File_resource_entity_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_entity_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_entity_id_proto_goTypes,
		DependencyIndexes: file_resource_entity_id_proto_depIdxs,
		MessageInfos:      file_resource_entity_id_proto_msgTypes,
	}.Build()
	File_resource_entity_id_proto = out.File
	file_resource_entity_id_proto_rawDesc = nil
	file_resource_entity_id_proto_goTypes = nil
	file_resource_entity_id_proto_depIdxs = nil
}
