// Copyright 2024 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: span_ingest_stats.proto

package chqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpanIngestStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exemplar    []byte              `protobuf:"bytes,1,opt,name=exemplar,proto3" json:"exemplar,omitempty"`
	EventsCount int64               `protobuf:"varint,2,opt,name=eventsCount,proto3" json:"eventsCount,omitempty"`
	SizeBytes   int64               `protobuf:"varint,3,opt,name=sizeBytes,proto3" json:"sizeBytes,omitempty"`
	Key         *SpanIngestStat_Key `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SpanIngestStat) Reset() {
	*x = SpanIngestStat{}
	mi := &file_span_ingest_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanIngestStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanIngestStat) ProtoMessage() {}

func (x *SpanIngestStat) ProtoReflect() protoreflect.Message {
	mi := &file_span_ingest_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanIngestStat.ProtoReflect.Descriptor instead.
func (*SpanIngestStat) Descriptor() ([]byte, []int) {
	return file_span_ingest_stats_proto_rawDescGZIP(), []int{0}
}

func (x *SpanIngestStat) GetExemplar() []byte {
	if x != nil {
		return x.Exemplar
	}
	return nil
}

func (x *SpanIngestStat) GetEventsCount() int64 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

func (x *SpanIngestStat) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SpanIngestStat) GetKey() *SpanIngestStat_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type SpanIngestStatsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats []*SpanIngestStat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
}

func (x *SpanIngestStatsList) Reset() {
	*x = SpanIngestStatsList{}
	mi := &file_span_ingest_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanIngestStatsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanIngestStatsList) ProtoMessage() {}

func (x *SpanIngestStatsList) ProtoReflect() protoreflect.Message {
	mi := &file_span_ingest_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanIngestStatsList.ProtoReflect.Descriptor instead.
func (*SpanIngestStatsList) Descriptor() ([]byte, []int) {
	return file_span_ingest_stats_proto_rawDescGZIP(), []int{1}
}

func (x *SpanIngestStatsList) GetStats() []*SpanIngestStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type SpanIngestStat_Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service     string       `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Fingerprint int64        `protobuf:"varint,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	TsHour      int64        `protobuf:"varint,3,opt,name=tsHour,proto3" json:"tsHour,omitempty"`
	Attributes  []*Attribute `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	CustomerId  string       `protobuf:"bytes,5,opt,name=customerId,proto3" json:"customerId,omitempty"`
	PhaseType   string       `protobuf:"bytes,6,opt,name=phaseType,proto3" json:"phaseType,omitempty"`
	ProcessorId string       `protobuf:"bytes,7,opt,name=processorId,proto3" json:"processorId,omitempty"`
	CollectorId string       `protobuf:"bytes,8,opt,name=collectorId,proto3" json:"collectorId,omitempty"`
}

func (x *SpanIngestStat_Key) Reset() {
	*x = SpanIngestStat_Key{}
	mi := &file_span_ingest_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanIngestStat_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanIngestStat_Key) ProtoMessage() {}

func (x *SpanIngestStat_Key) ProtoReflect() protoreflect.Message {
	mi := &file_span_ingest_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanIngestStat_Key.ProtoReflect.Descriptor instead.
func (*SpanIngestStat_Key) Descriptor() ([]byte, []int) {
	return file_span_ingest_stats_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SpanIngestStat_Key) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SpanIngestStat_Key) GetFingerprint() int64 {
	if x != nil {
		return x.Fingerprint
	}
	return 0
}

func (x *SpanIngestStat_Key) GetTsHour() int64 {
	if x != nil {
		return x.TsHour
	}
	return 0
}

func (x *SpanIngestStat_Key) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SpanIngestStat_Key) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SpanIngestStat_Key) GetPhaseType() string {
	if x != nil {
		return x.PhaseType
	}
	return ""
}

func (x *SpanIngestStat_Key) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *SpanIngestStat_Key) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

var File_span_ingest_stats_proto protoreflect.FileDescriptor

var file_span_ingest_stats_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x70, 0x61, 0x6e, 0x5f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x68, 0x71, 0x70, 0x62,
	0x1a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa9, 0x03, 0x0a, 0x0e, 0x53, 0x70, 0x61, 0x6e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x78, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x2b, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x63, 0x68, 0x71, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x6e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x1a, 0x8d, 0x02,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x73, 0x48, 0x6f, 0x75, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x74, 0x73, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x30, 0x0a, 0x0a, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x63, 0x68, 0x71, 0x70, 0x62, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x68, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x68, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x42, 0x0a,
	0x13, 0x53, 0x70, 0x61, 0x6e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x68, 0x71, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x6e,
	0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x63, 0x68, 0x71, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_span_ingest_stats_proto_rawDescOnce sync.Once
	file_span_ingest_stats_proto_rawDescData = file_span_ingest_stats_proto_rawDesc
)

func file_span_ingest_stats_proto_rawDescGZIP() []byte {
	file_span_ingest_stats_proto_rawDescOnce.Do(func() {
		file_span_ingest_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_span_ingest_stats_proto_rawDescData)
	})
	return file_span_ingest_stats_proto_rawDescData
}

var file_span_ingest_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_span_ingest_stats_proto_goTypes = []any{
	(*SpanIngestStat)(nil),      // 0: chqpb.SpanIngestStat
	(*SpanIngestStatsList)(nil), // 1: chqpb.SpanIngestStatsList
	(*SpanIngestStat_Key)(nil),  // 2: chqpb.SpanIngestStat.Key
	(*Attribute)(nil),           // 3: chqpb.Attribute
}
var file_span_ingest_stats_proto_depIdxs = []int32{
	2, // 0: chqpb.SpanIngestStat.key:type_name -> chqpb.SpanIngestStat.Key
	0, // 1: chqpb.SpanIngestStatsList.stats:type_name -> chqpb.SpanIngestStat
	3, // 2: chqpb.SpanIngestStat.Key.attributes:type_name -> chqpb.Attribute
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_span_ingest_stats_proto_init() }
func file_span_ingest_stats_proto_init() {
	if File_span_ingest_stats_proto != nil {
		return
	}
	file_attribute_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_span_ingest_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_span_ingest_stats_proto_goTypes,
		DependencyIndexes: file_span_ingest_stats_proto_depIdxs,
		MessageInfos:      file_span_ingest_stats_proto_msgTypes,
	}.Build()
	File_span_ingest_stats_proto = out.File
	file_span_ingest_stats_proto_rawDesc = nil
	file_span_ingest_stats_proto_goTypes = nil
	file_span_ingest_stats_proto_depIdxs = nil
}
