// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: span_ingest_stats.proto

package chqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpanIngestStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exemplar      []byte                 `protobuf:"bytes,1,opt,name=exemplar,proto3" json:"exemplar,omitempty"`
	EventsCount   int64                  `protobuf:"varint,2,opt,name=eventsCount,proto3" json:"eventsCount,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=sizeBytes,proto3" json:"sizeBytes,omitempty"`
	Key           *SpanIngestStat_Key    `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanIngestStat) Reset() {
	*x = SpanIngestStat{}
	mi := &file_span_ingest_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanIngestStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanIngestStat) ProtoMessage() {}

func (x *SpanIngestStat) ProtoReflect() protoreflect.Message {
	mi := &file_span_ingest_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanIngestStat.ProtoReflect.Descriptor instead.
func (*SpanIngestStat) Descriptor() ([]byte, []int) {
	return file_span_ingest_stats_proto_rawDescGZIP(), []int{0}
}

func (x *SpanIngestStat) GetExemplar() []byte {
	if x != nil {
		return x.Exemplar
	}
	return nil
}

func (x *SpanIngestStat) GetEventsCount() int64 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

func (x *SpanIngestStat) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SpanIngestStat) GetKey() *SpanIngestStat_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type SpanIngestStatsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*SpanIngestStat      `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanIngestStatsList) Reset() {
	*x = SpanIngestStatsList{}
	mi := &file_span_ingest_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanIngestStatsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanIngestStatsList) ProtoMessage() {}

func (x *SpanIngestStatsList) ProtoReflect() protoreflect.Message {
	mi := &file_span_ingest_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanIngestStatsList.ProtoReflect.Descriptor instead.
func (*SpanIngestStatsList) Descriptor() ([]byte, []int) {
	return file_span_ingest_stats_proto_rawDescGZIP(), []int{1}
}

func (x *SpanIngestStatsList) GetStats() []*SpanIngestStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type SpanIngestStat_Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Fingerprint   int64                  `protobuf:"varint,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	TsHour        int64                  `protobuf:"varint,3,opt,name=tsHour,proto3" json:"tsHour,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	CustomerId    string                 `protobuf:"bytes,5,opt,name=customerId,proto3" json:"customerId,omitempty"`
	PhaseType     string                 `protobuf:"bytes,6,opt,name=phaseType,proto3" json:"phaseType,omitempty"`
	ProcessorId   string                 `protobuf:"bytes,7,opt,name=processorId,proto3" json:"processorId,omitempty"`
	CollectorId   string                 `protobuf:"bytes,8,opt,name=collectorId,proto3" json:"collectorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanIngestStat_Key) Reset() {
	*x = SpanIngestStat_Key{}
	mi := &file_span_ingest_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanIngestStat_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanIngestStat_Key) ProtoMessage() {}

func (x *SpanIngestStat_Key) ProtoReflect() protoreflect.Message {
	mi := &file_span_ingest_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanIngestStat_Key.ProtoReflect.Descriptor instead.
func (*SpanIngestStat_Key) Descriptor() ([]byte, []int) {
	return file_span_ingest_stats_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SpanIngestStat_Key) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SpanIngestStat_Key) GetFingerprint() int64 {
	if x != nil {
		return x.Fingerprint
	}
	return 0
}

func (x *SpanIngestStat_Key) GetTsHour() int64 {
	if x != nil {
		return x.TsHour
	}
	return 0
}

func (x *SpanIngestStat_Key) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SpanIngestStat_Key) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SpanIngestStat_Key) GetPhaseType() string {
	if x != nil {
		return x.PhaseType
	}
	return ""
}

func (x *SpanIngestStat_Key) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *SpanIngestStat_Key) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

var File_span_ingest_stats_proto protoreflect.FileDescriptor

const file_span_ingest_stats_proto_rawDesc = "" +
	"\n" +
	"\x17span_ingest_stats.proto\x12\x05chqpb\x1a\x0fattribute.proto\"\xa9\x03\n" +
	"\x0eSpanIngestStat\x12\x1a\n" +
	"\bexemplar\x18\x01 \x01(\fR\bexemplar\x12 \n" +
	"\veventsCount\x18\x02 \x01(\x03R\veventsCount\x12\x1c\n" +
	"\tsizeBytes\x18\x03 \x01(\x03R\tsizeBytes\x12+\n" +
	"\x03key\x18\x04 \x01(\v2\x19.chqpb.SpanIngestStat.KeyR\x03key\x1a\x8d\x02\n" +
	"\x03Key\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\x03R\vfingerprint\x12\x16\n" +
	"\x06tsHour\x18\x03 \x01(\x03R\x06tsHour\x120\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\x10.chqpb.AttributeR\n" +
	"attributes\x12\x1e\n" +
	"\n" +
	"customerId\x18\x05 \x01(\tR\n" +
	"customerId\x12\x1c\n" +
	"\tphaseType\x18\x06 \x01(\tR\tphaseType\x12 \n" +
	"\vprocessorId\x18\a \x01(\tR\vprocessorId\x12 \n" +
	"\vcollectorId\x18\b \x01(\tR\vcollectorId\"B\n" +
	"\x13SpanIngestStatsList\x12+\n" +
	"\x05stats\x18\x01 \x03(\v2\x15.chqpb.SpanIngestStatR\x05statsB\tZ\a.;chqpbb\x06proto3"

var (
	file_span_ingest_stats_proto_rawDescOnce sync.Once
	file_span_ingest_stats_proto_rawDescData []byte
)

func file_span_ingest_stats_proto_rawDescGZIP() []byte {
	file_span_ingest_stats_proto_rawDescOnce.Do(func() {
		file_span_ingest_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_span_ingest_stats_proto_rawDesc), len(file_span_ingest_stats_proto_rawDesc)))
	})
	return file_span_ingest_stats_proto_rawDescData
}

var file_span_ingest_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_span_ingest_stats_proto_goTypes = []any{
	(*SpanIngestStat)(nil),      // 0: chqpb.SpanIngestStat
	(*SpanIngestStatsList)(nil), // 1: chqpb.SpanIngestStatsList
	(*SpanIngestStat_Key)(nil),  // 2: chqpb.SpanIngestStat.Key
	(*Attribute)(nil),           // 3: chqpb.Attribute
}
var file_span_ingest_stats_proto_depIdxs = []int32{
	2, // 0: chqpb.SpanIngestStat.key:type_name -> chqpb.SpanIngestStat.Key
	0, // 1: chqpb.SpanIngestStatsList.stats:type_name -> chqpb.SpanIngestStat
	3, // 2: chqpb.SpanIngestStat.Key.attributes:type_name -> chqpb.Attribute
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_span_ingest_stats_proto_init() }
func file_span_ingest_stats_proto_init() {
	if File_span_ingest_stats_proto != nil {
		return
	}
	file_attribute_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_span_ingest_stats_proto_rawDesc), len(file_span_ingest_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_span_ingest_stats_proto_goTypes,
		DependencyIndexes: file_span_ingest_stats_proto_depIdxs,
		MessageInfos:      file_span_ingest_stats_proto_msgTypes,
	}.Build()
	File_span_ingest_stats_proto = out.File
	file_span_ingest_stats_proto_goTypes = nil
	file_span_ingest_stats_proto_depIdxs = nil
}
