// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: apps_deployment.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppsDeploymentSummary summarizes a Kubernetes apps/v1 Deployment.
type AppsDeploymentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseObject    *BaseObject            `protobuf:"bytes,1,opt,name=base_object,json=baseObject,proto3" json:"base_object,omitempty"`
	Spec          *AppsDeploymentSpec    `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *AppDeploymentStatus   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsDeploymentSummary) Reset() {
	*x = AppsDeploymentSummary{}
	mi := &file_apps_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsDeploymentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsDeploymentSummary) ProtoMessage() {}

func (x *AppsDeploymentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_apps_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsDeploymentSummary.ProtoReflect.Descriptor instead.
func (*AppsDeploymentSummary) Descriptor() ([]byte, []int) {
	return file_apps_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *AppsDeploymentSummary) GetBaseObject() *BaseObject {
	if x != nil {
		return x.BaseObject
	}
	return nil
}

func (x *AppsDeploymentSummary) GetSpec() *AppsDeploymentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AppsDeploymentSummary) GetStatus() *AppDeploymentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AppsDeploymentSummarySpec is the spec of a AppsDeploymentSummary.
type AppsDeploymentSpec struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Replicas int32                  `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// "template" is the pod template of the Deployment.
	Template      *AppsDeploymentTemplate `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsDeploymentSpec) Reset() {
	*x = AppsDeploymentSpec{}
	mi := &file_apps_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsDeploymentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsDeploymentSpec) ProtoMessage() {}

func (x *AppsDeploymentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_apps_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsDeploymentSpec.ProtoReflect.Descriptor instead.
func (*AppsDeploymentSpec) Descriptor() ([]byte, []int) {
	return file_apps_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *AppsDeploymentSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AppsDeploymentSpec) GetTemplate() *AppsDeploymentTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// AppsDeploymentSummaryStatus is the status of a AppsDeploymentSummary.
type AppsDeploymentTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *BaseObject            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PodSpec       *PodSpec               `protobuf:"bytes,2,opt,name=pod_spec,json=podSpec,proto3" json:"pod_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsDeploymentTemplate) Reset() {
	*x = AppsDeploymentTemplate{}
	mi := &file_apps_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsDeploymentTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsDeploymentTemplate) ProtoMessage() {}

func (x *AppsDeploymentTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_apps_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsDeploymentTemplate.ProtoReflect.Descriptor instead.
func (*AppsDeploymentTemplate) Descriptor() ([]byte, []int) {
	return file_apps_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *AppsDeploymentTemplate) GetMetadata() *BaseObject {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AppsDeploymentTemplate) GetPodSpec() *PodSpec {
	if x != nil {
		return x.PodSpec
	}
	return nil
}

// AppDeploymentStatus is the status of a Kubernetes apps/v1 Deployment.
type AppDeploymentStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of non-terminated pods targeted by this deployment (their labels match the selector).
	Replicas int32 `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// Total number of non-terminated pods targeted by this deployment that have the desired template spec.
	UpdatedReplicas int32 `protobuf:"varint,2,opt,name=updated_replicas,json=updatedReplicas,proto3" json:"updated_replicas,omitempty"`
	// readyReplicas is the number of pods targeted by this Deployment with a Ready Condition.
	ReadyReplicas int32 `protobuf:"varint,3,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// Total number of available pods (ready for at least minReadySeconds) targeted by this deployment.
	AvailableReplicas int32 `protobuf:"varint,4,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	// Total number of unavailable pods targeted by this deployment. This is the total number of
	// pods that are still required for the deployment to have 100% available capacity. They may
	// either be pods that are running but not yet available or pods that still have not been created.
	UnavailableReplicas int32 `protobuf:"varint,5,opt,name=unavailable_replicas,json=unavailableReplicas,proto3" json:"unavailable_replicas,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AppDeploymentStatus) Reset() {
	*x = AppDeploymentStatus{}
	mi := &file_apps_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppDeploymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDeploymentStatus) ProtoMessage() {}

func (x *AppDeploymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_apps_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDeploymentStatus.ProtoReflect.Descriptor instead.
func (*AppDeploymentStatus) Descriptor() ([]byte, []int) {
	return file_apps_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *AppDeploymentStatus) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AppDeploymentStatus) GetUpdatedReplicas() int32 {
	if x != nil {
		return x.UpdatedReplicas
	}
	return 0
}

func (x *AppDeploymentStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *AppDeploymentStatus) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *AppDeploymentStatus) GetUnavailableReplicas() int32 {
	if x != nil {
		return x.UnavailableReplicas
	}
	return 0
}

var File_apps_deployment_proto protoreflect.FileDescriptor

const file_apps_deployment_proto_rawDesc = "" +
	"\n" +
	"\x15apps_deployment.proto\x12\agraphpb\x1a\n" +
	"base.proto\x1a\tpod.proto\"\xb4\x01\n" +
	"\x15AppsDeploymentSummary\x124\n" +
	"\vbase_object\x18\x01 \x01(\v2\x13.graphpb.BaseObjectR\n" +
	"baseObject\x12/\n" +
	"\x04spec\x18\x02 \x01(\v2\x1b.graphpb.AppsDeploymentSpecR\x04spec\x124\n" +
	"\x06status\x18\x03 \x01(\v2\x1c.graphpb.AppDeploymentStatusR\x06status\"m\n" +
	"\x12AppsDeploymentSpec\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12;\n" +
	"\btemplate\x18\x02 \x01(\v2\x1f.graphpb.AppsDeploymentTemplateR\btemplate\"v\n" +
	"\x16AppsDeploymentTemplate\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.graphpb.BaseObjectR\bmetadata\x12+\n" +
	"\bpod_spec\x18\x02 \x01(\v2\x10.graphpb.PodSpecR\apodSpec\"\xe5\x01\n" +
	"\x13AppDeploymentStatus\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12)\n" +
	"\x10updated_replicas\x18\x02 \x01(\x05R\x0fupdatedReplicas\x12%\n" +
	"\x0eready_replicas\x18\x03 \x01(\x05R\rreadyReplicas\x12-\n" +
	"\x12available_replicas\x18\x04 \x01(\x05R\x11availableReplicas\x121\n" +
	"\x14unavailable_replicas\x18\x05 \x01(\x05R\x13unavailableReplicasB3Z1github.com/cardinalhq/oteltools/pkg/graph/graphpbb\x06proto3"

var (
	file_apps_deployment_proto_rawDescOnce sync.Once
	file_apps_deployment_proto_rawDescData []byte
)

func file_apps_deployment_proto_rawDescGZIP() []byte {
	file_apps_deployment_proto_rawDescOnce.Do(func() {
		file_apps_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_deployment_proto_rawDesc), len(file_apps_deployment_proto_rawDesc)))
	})
	return file_apps_deployment_proto_rawDescData
}

var file_apps_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apps_deployment_proto_goTypes = []any{
	(*AppsDeploymentSummary)(nil),  // 0: graphpb.AppsDeploymentSummary
	(*AppsDeploymentSpec)(nil),     // 1: graphpb.AppsDeploymentSpec
	(*AppsDeploymentTemplate)(nil), // 2: graphpb.AppsDeploymentTemplate
	(*AppDeploymentStatus)(nil),    // 3: graphpb.AppDeploymentStatus
	(*BaseObject)(nil),             // 4: graphpb.BaseObject
	(*PodSpec)(nil),                // 5: graphpb.PodSpec
}
var file_apps_deployment_proto_depIdxs = []int32{
	4, // 0: graphpb.AppsDeploymentSummary.base_object:type_name -> graphpb.BaseObject
	1, // 1: graphpb.AppsDeploymentSummary.spec:type_name -> graphpb.AppsDeploymentSpec
	3, // 2: graphpb.AppsDeploymentSummary.status:type_name -> graphpb.AppDeploymentStatus
	2, // 3: graphpb.AppsDeploymentSpec.template:type_name -> graphpb.AppsDeploymentTemplate
	4, // 4: graphpb.AppsDeploymentTemplate.metadata:type_name -> graphpb.BaseObject
	5, // 5: graphpb.AppsDeploymentTemplate.pod_spec:type_name -> graphpb.PodSpec
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apps_deployment_proto_init() }
func file_apps_deployment_proto_init() {
	if File_apps_deployment_proto != nil {
		return
	}
	file_base_proto_init()
	file_pod_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_deployment_proto_rawDesc), len(file_apps_deployment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_deployment_proto_goTypes,
		DependencyIndexes: file_apps_deployment_proto_depIdxs,
		MessageInfos:      file_apps_deployment_proto_msgTypes,
	}.Build()
	File_apps_deployment_proto = out.File
	file_apps_deployment_proto_goTypes = nil
	file_apps_deployment_proto_depIdxs = nil
}
