// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: apps_replicaset.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppsReplicaSetSummary summarizes a Kubernetes apps/v1 ReplicaSet.
type AppsReplicaSetSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseObject    *BaseObject            `protobuf:"bytes,1,opt,name=base_object,json=baseObject,proto3" json:"base_object,omitempty"`
	Spec          *AppsReplicaSetSpec    `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *AppReplicaSetStatus   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsReplicaSetSummary) Reset() {
	*x = AppsReplicaSetSummary{}
	mi := &file_apps_replicaset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsReplicaSetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsReplicaSetSummary) ProtoMessage() {}

func (x *AppsReplicaSetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_apps_replicaset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsReplicaSetSummary.ProtoReflect.Descriptor instead.
func (*AppsReplicaSetSummary) Descriptor() ([]byte, []int) {
	return file_apps_replicaset_proto_rawDescGZIP(), []int{0}
}

func (x *AppsReplicaSetSummary) GetBaseObject() *BaseObject {
	if x != nil {
		return x.BaseObject
	}
	return nil
}

func (x *AppsReplicaSetSummary) GetSpec() *AppsReplicaSetSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AppsReplicaSetSummary) GetStatus() *AppReplicaSetStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AppsReplicaSetSummarySpec is the spec of a AppsReplicaSetSummary.
type AppsReplicaSetSpec struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Replicas int32                  `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// "template" is the pod template of the ReplicaSet.
	Template      *AppsReplicaSetTemplate `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsReplicaSetSpec) Reset() {
	*x = AppsReplicaSetSpec{}
	mi := &file_apps_replicaset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsReplicaSetSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsReplicaSetSpec) ProtoMessage() {}

func (x *AppsReplicaSetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_apps_replicaset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsReplicaSetSpec.ProtoReflect.Descriptor instead.
func (*AppsReplicaSetSpec) Descriptor() ([]byte, []int) {
	return file_apps_replicaset_proto_rawDescGZIP(), []int{1}
}

func (x *AppsReplicaSetSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AppsReplicaSetSpec) GetTemplate() *AppsReplicaSetTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// AppsReplicaSetSummaryStatus is the status of a AppsReplicaSetSummary.
type AppsReplicaSetTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *BaseObject            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PodSpec       *PodSpec               `protobuf:"bytes,2,opt,name=pod_spec,json=podSpec,proto3" json:"pod_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsReplicaSetTemplate) Reset() {
	*x = AppsReplicaSetTemplate{}
	mi := &file_apps_replicaset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsReplicaSetTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsReplicaSetTemplate) ProtoMessage() {}

func (x *AppsReplicaSetTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_apps_replicaset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsReplicaSetTemplate.ProtoReflect.Descriptor instead.
func (*AppsReplicaSetTemplate) Descriptor() ([]byte, []int) {
	return file_apps_replicaset_proto_rawDescGZIP(), []int{2}
}

func (x *AppsReplicaSetTemplate) GetMetadata() *BaseObject {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AppsReplicaSetTemplate) GetPodSpec() *PodSpec {
	if x != nil {
		return x.PodSpec
	}
	return nil
}

// AppReplicaSetStatus is the status of a Kubernetes apps/v1 ReplicaSet.
type AppReplicaSetStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replicas is the most recently observed number of replicas.
	// More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller
	Replicas int32 `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// The number of pods that have labels matching the labels of the pod template of the replicaset.
	FullyLabeledReplicas int32 `protobuf:"varint,2,opt,name=fully_labeled_replicas,json=fullyLabeledReplicas,proto3" json:"fully_labeled_replicas,omitempty"`
	// readyReplicas is the number of pods targeted by this ReplicaSet with a Ready Condition.
	ReadyReplicas int32 `protobuf:"varint,3,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// The number of available replicas (ready for at least minReadySeconds) for this replica set.
	AvailableReplicas int32 `protobuf:"varint,4,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppReplicaSetStatus) Reset() {
	*x = AppReplicaSetStatus{}
	mi := &file_apps_replicaset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppReplicaSetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppReplicaSetStatus) ProtoMessage() {}

func (x *AppReplicaSetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_apps_replicaset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppReplicaSetStatus.ProtoReflect.Descriptor instead.
func (*AppReplicaSetStatus) Descriptor() ([]byte, []int) {
	return file_apps_replicaset_proto_rawDescGZIP(), []int{3}
}

func (x *AppReplicaSetStatus) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AppReplicaSetStatus) GetFullyLabeledReplicas() int32 {
	if x != nil {
		return x.FullyLabeledReplicas
	}
	return 0
}

func (x *AppReplicaSetStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *AppReplicaSetStatus) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

var File_apps_replicaset_proto protoreflect.FileDescriptor

const file_apps_replicaset_proto_rawDesc = "" +
	"\n" +
	"\x15apps_replicaset.proto\x12\agraphpb\x1a\n" +
	"base.proto\x1a\tpod.proto\"\xb4\x01\n" +
	"\x15AppsReplicaSetSummary\x124\n" +
	"\vbase_object\x18\x01 \x01(\v2\x13.graphpb.BaseObjectR\n" +
	"baseObject\x12/\n" +
	"\x04spec\x18\x02 \x01(\v2\x1b.graphpb.AppsReplicaSetSpecR\x04spec\x124\n" +
	"\x06status\x18\x03 \x01(\v2\x1c.graphpb.AppReplicaSetStatusR\x06status\"m\n" +
	"\x12AppsReplicaSetSpec\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12;\n" +
	"\btemplate\x18\x02 \x01(\v2\x1f.graphpb.AppsReplicaSetTemplateR\btemplate\"v\n" +
	"\x16AppsReplicaSetTemplate\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.graphpb.BaseObjectR\bmetadata\x12+\n" +
	"\bpod_spec\x18\x02 \x01(\v2\x10.graphpb.PodSpecR\apodSpec\"\xbd\x01\n" +
	"\x13AppReplicaSetStatus\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x124\n" +
	"\x16fully_labeled_replicas\x18\x02 \x01(\x05R\x14fullyLabeledReplicas\x12%\n" +
	"\x0eready_replicas\x18\x03 \x01(\x05R\rreadyReplicas\x12-\n" +
	"\x12available_replicas\x18\x04 \x01(\x05R\x11availableReplicasB3Z1github.com/cardinalhq/oteltools/pkg/graph/graphpbb\x06proto3"

var (
	file_apps_replicaset_proto_rawDescOnce sync.Once
	file_apps_replicaset_proto_rawDescData []byte
)

func file_apps_replicaset_proto_rawDescGZIP() []byte {
	file_apps_replicaset_proto_rawDescOnce.Do(func() {
		file_apps_replicaset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_replicaset_proto_rawDesc), len(file_apps_replicaset_proto_rawDesc)))
	})
	return file_apps_replicaset_proto_rawDescData
}

var file_apps_replicaset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apps_replicaset_proto_goTypes = []any{
	(*AppsReplicaSetSummary)(nil),  // 0: graphpb.AppsReplicaSetSummary
	(*AppsReplicaSetSpec)(nil),     // 1: graphpb.AppsReplicaSetSpec
	(*AppsReplicaSetTemplate)(nil), // 2: graphpb.AppsReplicaSetTemplate
	(*AppReplicaSetStatus)(nil),    // 3: graphpb.AppReplicaSetStatus
	(*BaseObject)(nil),             // 4: graphpb.BaseObject
	(*PodSpec)(nil),                // 5: graphpb.PodSpec
}
var file_apps_replicaset_proto_depIdxs = []int32{
	4, // 0: graphpb.AppsReplicaSetSummary.base_object:type_name -> graphpb.BaseObject
	1, // 1: graphpb.AppsReplicaSetSummary.spec:type_name -> graphpb.AppsReplicaSetSpec
	3, // 2: graphpb.AppsReplicaSetSummary.status:type_name -> graphpb.AppReplicaSetStatus
	2, // 3: graphpb.AppsReplicaSetSpec.template:type_name -> graphpb.AppsReplicaSetTemplate
	4, // 4: graphpb.AppsReplicaSetTemplate.metadata:type_name -> graphpb.BaseObject
	5, // 5: graphpb.AppsReplicaSetTemplate.pod_spec:type_name -> graphpb.PodSpec
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apps_replicaset_proto_init() }
func file_apps_replicaset_proto_init() {
	if File_apps_replicaset_proto != nil {
		return
	}
	file_base_proto_init()
	file_pod_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_replicaset_proto_rawDesc), len(file_apps_replicaset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_replicaset_proto_goTypes,
		DependencyIndexes: file_apps_replicaset_proto_depIdxs,
		MessageInfos:      file_apps_replicaset_proto_msgTypes,
	}.Build()
	File_apps_replicaset_proto = out.File
	file_apps_replicaset_proto_goTypes = nil
	file_apps_replicaset_proto_depIdxs = nil
}
