// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: apps_statefulset.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppsStatefulSetSummary summarizes a Kubernetes apps/v1 StatefulSet.
type AppsStatefulSetSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseObject    *BaseObject            `protobuf:"bytes,1,opt,name=base_object,json=baseObject,proto3" json:"base_object,omitempty"`
	Spec          *AppsStatefulSetSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *AppStatefulSetStatus  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsStatefulSetSummary) Reset() {
	*x = AppsStatefulSetSummary{}
	mi := &file_apps_statefulset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsStatefulSetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsStatefulSetSummary) ProtoMessage() {}

func (x *AppsStatefulSetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_apps_statefulset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsStatefulSetSummary.ProtoReflect.Descriptor instead.
func (*AppsStatefulSetSummary) Descriptor() ([]byte, []int) {
	return file_apps_statefulset_proto_rawDescGZIP(), []int{0}
}

func (x *AppsStatefulSetSummary) GetBaseObject() *BaseObject {
	if x != nil {
		return x.BaseObject
	}
	return nil
}

func (x *AppsStatefulSetSummary) GetSpec() *AppsStatefulSetSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AppsStatefulSetSummary) GetStatus() *AppStatefulSetStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AppsStatefulSetSummarySpec is the spec of a AppsStatefulSetSummary.
type AppsStatefulSetSpec struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Replicas int32                  `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// "template" is the pod template of the StatefulSet.
	Template *AppsStatefulSetTemplate `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// "service_name" is the name of the service that governs the StatefulSet.
	ServiceName   string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsStatefulSetSpec) Reset() {
	*x = AppsStatefulSetSpec{}
	mi := &file_apps_statefulset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsStatefulSetSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsStatefulSetSpec) ProtoMessage() {}

func (x *AppsStatefulSetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_apps_statefulset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsStatefulSetSpec.ProtoReflect.Descriptor instead.
func (*AppsStatefulSetSpec) Descriptor() ([]byte, []int) {
	return file_apps_statefulset_proto_rawDescGZIP(), []int{1}
}

func (x *AppsStatefulSetSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AppsStatefulSetSpec) GetTemplate() *AppsStatefulSetTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *AppsStatefulSetSpec) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// AppsStatefulSetSummaryStatus is the status of a AppsStatefulSetSummary.
type AppsStatefulSetTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *BaseObject            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PodSpec       *PodSpec               `protobuf:"bytes,2,opt,name=pod_spec,json=podSpec,proto3" json:"pod_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsStatefulSetTemplate) Reset() {
	*x = AppsStatefulSetTemplate{}
	mi := &file_apps_statefulset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsStatefulSetTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsStatefulSetTemplate) ProtoMessage() {}

func (x *AppsStatefulSetTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_apps_statefulset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsStatefulSetTemplate.ProtoReflect.Descriptor instead.
func (*AppsStatefulSetTemplate) Descriptor() ([]byte, []int) {
	return file_apps_statefulset_proto_rawDescGZIP(), []int{2}
}

func (x *AppsStatefulSetTemplate) GetMetadata() *BaseObject {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AppsStatefulSetTemplate) GetPodSpec() *PodSpec {
	if x != nil {
		return x.PodSpec
	}
	return nil
}

// AppStatefulSetStatus is the status of a Kubernetes apps/v1 StatefulSet.
type AppStatefulSetStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// replicas is the number of Pods created by the StatefulSet controller.
	Replicas int32 `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// readyReplicas is the number of pods created for this StatefulSet with a Ready Condition.
	ReadyReplicas int32 `protobuf:"varint,2,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// currentReplicas is the number of Pods created by the StatefulSet controller from the StatefulSet version
	// indicated by currentRevision.
	CurrentReplicas int32 `protobuf:"varint,3,opt,name=current_replicas,json=currentReplicas,proto3" json:"current_replicas,omitempty"`
	// updatedReplicas is the number of Pods created by the StatefulSet controller from the StatefulSet version
	// indicated by updateRevision.
	UpdatedReplicas int32 `protobuf:"varint,4,opt,name=updated_replicas,json=updatedReplicas,proto3" json:"updated_replicas,omitempty"`
	// currentRevision, if not empty, indicates the version of the StatefulSet used to generate Pods in the
	// sequence [0,currentReplicas).
	CurrentRevision string `protobuf:"bytes,5,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	// updateRevision, if not empty, indicates the version of the StatefulSet used to generate Pods in the sequence
	// [replicas-updatedReplicas,replicas)
	UpdateRevision string `protobuf:"bytes,6,opt,name=update_revision,json=updateRevision,proto3" json:"update_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppStatefulSetStatus) Reset() {
	*x = AppStatefulSetStatus{}
	mi := &file_apps_statefulset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppStatefulSetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatefulSetStatus) ProtoMessage() {}

func (x *AppStatefulSetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_apps_statefulset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatefulSetStatus.ProtoReflect.Descriptor instead.
func (*AppStatefulSetStatus) Descriptor() ([]byte, []int) {
	return file_apps_statefulset_proto_rawDescGZIP(), []int{3}
}

func (x *AppStatefulSetStatus) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AppStatefulSetStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *AppStatefulSetStatus) GetCurrentReplicas() int32 {
	if x != nil {
		return x.CurrentReplicas
	}
	return 0
}

func (x *AppStatefulSetStatus) GetUpdatedReplicas() int32 {
	if x != nil {
		return x.UpdatedReplicas
	}
	return 0
}

func (x *AppStatefulSetStatus) GetCurrentRevision() string {
	if x != nil {
		return x.CurrentRevision
	}
	return ""
}

func (x *AppStatefulSetStatus) GetUpdateRevision() string {
	if x != nil {
		return x.UpdateRevision
	}
	return ""
}

var File_apps_statefulset_proto protoreflect.FileDescriptor

const file_apps_statefulset_proto_rawDesc = "" +
	"\n" +
	"\x16apps_statefulset.proto\x12\agraphpb\x1a\n" +
	"base.proto\x1a\tpod.proto\"\xb7\x01\n" +
	"\x16AppsStatefulSetSummary\x124\n" +
	"\vbase_object\x18\x01 \x01(\v2\x13.graphpb.BaseObjectR\n" +
	"baseObject\x120\n" +
	"\x04spec\x18\x02 \x01(\v2\x1c.graphpb.AppsStatefulSetSpecR\x04spec\x125\n" +
	"\x06status\x18\x03 \x01(\v2\x1d.graphpb.AppStatefulSetStatusR\x06status\"\x92\x01\n" +
	"\x13AppsStatefulSetSpec\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12<\n" +
	"\btemplate\x18\x02 \x01(\v2 .graphpb.AppsStatefulSetTemplateR\btemplate\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"w\n" +
	"\x17AppsStatefulSetTemplate\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.graphpb.BaseObjectR\bmetadata\x12+\n" +
	"\bpod_spec\x18\x02 \x01(\v2\x10.graphpb.PodSpecR\apodSpec\"\x83\x02\n" +
	"\x14AppStatefulSetStatus\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12%\n" +
	"\x0eready_replicas\x18\x02 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10current_replicas\x18\x03 \x01(\x05R\x0fcurrentReplicas\x12)\n" +
	"\x10updated_replicas\x18\x04 \x01(\x05R\x0fupdatedReplicas\x12)\n" +
	"\x10current_revision\x18\x05 \x01(\tR\x0fcurrentRevision\x12'\n" +
	"\x0fupdate_revision\x18\x06 \x01(\tR\x0eupdateRevisionB3Z1github.com/cardinalhq/oteltools/pkg/graph/graphpbb\x06proto3"

var (
	file_apps_statefulset_proto_rawDescOnce sync.Once
	file_apps_statefulset_proto_rawDescData []byte
)

func file_apps_statefulset_proto_rawDescGZIP() []byte {
	file_apps_statefulset_proto_rawDescOnce.Do(func() {
		file_apps_statefulset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_statefulset_proto_rawDesc), len(file_apps_statefulset_proto_rawDesc)))
	})
	return file_apps_statefulset_proto_rawDescData
}

var file_apps_statefulset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apps_statefulset_proto_goTypes = []any{
	(*AppsStatefulSetSummary)(nil),  // 0: graphpb.AppsStatefulSetSummary
	(*AppsStatefulSetSpec)(nil),     // 1: graphpb.AppsStatefulSetSpec
	(*AppsStatefulSetTemplate)(nil), // 2: graphpb.AppsStatefulSetTemplate
	(*AppStatefulSetStatus)(nil),    // 3: graphpb.AppStatefulSetStatus
	(*BaseObject)(nil),              // 4: graphpb.BaseObject
	(*PodSpec)(nil),                 // 5: graphpb.PodSpec
}
var file_apps_statefulset_proto_depIdxs = []int32{
	4, // 0: graphpb.AppsStatefulSetSummary.base_object:type_name -> graphpb.BaseObject
	1, // 1: graphpb.AppsStatefulSetSummary.spec:type_name -> graphpb.AppsStatefulSetSpec
	3, // 2: graphpb.AppsStatefulSetSummary.status:type_name -> graphpb.AppStatefulSetStatus
	2, // 3: graphpb.AppsStatefulSetSpec.template:type_name -> graphpb.AppsStatefulSetTemplate
	4, // 4: graphpb.AppsStatefulSetTemplate.metadata:type_name -> graphpb.BaseObject
	5, // 5: graphpb.AppsStatefulSetTemplate.pod_spec:type_name -> graphpb.PodSpec
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apps_statefulset_proto_init() }
func file_apps_statefulset_proto_init() {
	if File_apps_statefulset_proto != nil {
		return
	}
	file_base_proto_init()
	file_pod_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_statefulset_proto_rawDesc), len(file_apps_statefulset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_statefulset_proto_goTypes,
		DependencyIndexes: file_apps_statefulset_proto_depIdxs,
		MessageInfos:      file_apps_statefulset_proto_msgTypes,
	}.Build()
	File_apps_statefulset_proto = out.File
	file_apps_statefulset_proto_goTypes = nil
	file_apps_statefulset_proto_depIdxs = nil
}
