// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: autoscaling_hpa.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AutoscalingHpaSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseObject    *BaseObject            `protobuf:"bytes,1,opt,name=base_object,json=baseObject,proto3" json:"base_object,omitempty"`
	Spec          *AutoscalingHpaSpec    `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *AutoscalingHpaStatus  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoscalingHpaSummary) Reset() {
	*x = AutoscalingHpaSummary{}
	mi := &file_autoscaling_hpa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoscalingHpaSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoscalingHpaSummary) ProtoMessage() {}

func (x *AutoscalingHpaSummary) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaling_hpa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoscalingHpaSummary.ProtoReflect.Descriptor instead.
func (*AutoscalingHpaSummary) Descriptor() ([]byte, []int) {
	return file_autoscaling_hpa_proto_rawDescGZIP(), []int{0}
}

func (x *AutoscalingHpaSummary) GetBaseObject() *BaseObject {
	if x != nil {
		return x.BaseObject
	}
	return nil
}

func (x *AutoscalingHpaSummary) GetSpec() *AutoscalingHpaSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AutoscalingHpaSummary) GetStatus() *AutoscalingHpaStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AutoscalingHpaSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinReplicas   int32                  `protobuf:"varint,1,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	MaxReplicas   int32                  `protobuf:"varint,2,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	Target        *AutoscalingHpaTarget  `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoscalingHpaSpec) Reset() {
	*x = AutoscalingHpaSpec{}
	mi := &file_autoscaling_hpa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoscalingHpaSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoscalingHpaSpec) ProtoMessage() {}

func (x *AutoscalingHpaSpec) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaling_hpa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoscalingHpaSpec.ProtoReflect.Descriptor instead.
func (*AutoscalingHpaSpec) Descriptor() ([]byte, []int) {
	return file_autoscaling_hpa_proto_rawDescGZIP(), []int{1}
}

func (x *AutoscalingHpaSpec) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *AutoscalingHpaSpec) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *AutoscalingHpaSpec) GetTarget() *AutoscalingHpaTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

type AutoscalingHpaTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoscalingHpaTarget) Reset() {
	*x = AutoscalingHpaTarget{}
	mi := &file_autoscaling_hpa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoscalingHpaTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoscalingHpaTarget) ProtoMessage() {}

func (x *AutoscalingHpaTarget) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaling_hpa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoscalingHpaTarget.ProtoReflect.Descriptor instead.
func (*AutoscalingHpaTarget) Descriptor() ([]byte, []int) {
	return file_autoscaling_hpa_proto_rawDescGZIP(), []int{2}
}

func (x *AutoscalingHpaTarget) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AutoscalingHpaTarget) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AutoscalingHpaTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AutoscalingHpaStatus struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	CurrentReplicas int32                      `protobuf:"varint,1,opt,name=current_replicas,json=currentReplicas,proto3" json:"current_replicas,omitempty"`
	DesiredReplicas int32                      `protobuf:"varint,2,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	Conditions      []*AutoscalingHpaCondition `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	LasScaleTime    *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=las_scale_time,json=lasScaleTime,proto3" json:"las_scale_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AutoscalingHpaStatus) Reset() {
	*x = AutoscalingHpaStatus{}
	mi := &file_autoscaling_hpa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoscalingHpaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoscalingHpaStatus) ProtoMessage() {}

func (x *AutoscalingHpaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaling_hpa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoscalingHpaStatus.ProtoReflect.Descriptor instead.
func (*AutoscalingHpaStatus) Descriptor() ([]byte, []int) {
	return file_autoscaling_hpa_proto_rawDescGZIP(), []int{3}
}

func (x *AutoscalingHpaStatus) GetCurrentReplicas() int32 {
	if x != nil {
		return x.CurrentReplicas
	}
	return 0
}

func (x *AutoscalingHpaStatus) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *AutoscalingHpaStatus) GetConditions() []*AutoscalingHpaCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *AutoscalingHpaStatus) GetLasScaleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LasScaleTime
	}
	return nil
}

type AutoscalingHpaCondition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	Reason             string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AutoscalingHpaCondition) Reset() {
	*x = AutoscalingHpaCondition{}
	mi := &file_autoscaling_hpa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoscalingHpaCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoscalingHpaCondition) ProtoMessage() {}

func (x *AutoscalingHpaCondition) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaling_hpa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoscalingHpaCondition.ProtoReflect.Descriptor instead.
func (*AutoscalingHpaCondition) Descriptor() ([]byte, []int) {
	return file_autoscaling_hpa_proto_rawDescGZIP(), []int{4}
}

func (x *AutoscalingHpaCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AutoscalingHpaCondition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AutoscalingHpaCondition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

func (x *AutoscalingHpaCondition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AutoscalingHpaCondition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_autoscaling_hpa_proto protoreflect.FileDescriptor

const file_autoscaling_hpa_proto_rawDesc = "" +
	"\n" +
	"\x15autoscaling_hpa.proto\x12\agraphpb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"base.proto\"\xb5\x01\n" +
	"\x15AutoscalingHpaSummary\x124\n" +
	"\vbase_object\x18\x01 \x01(\v2\x13.graphpb.BaseObjectR\n" +
	"baseObject\x12/\n" +
	"\x04spec\x18\x02 \x01(\v2\x1b.graphpb.AutoscalingHpaSpecR\x04spec\x125\n" +
	"\x06status\x18\x03 \x01(\v2\x1d.graphpb.AutoscalingHpaStatusR\x06status\"\x91\x01\n" +
	"\x12AutoscalingHpaSpec\x12!\n" +
	"\fmin_replicas\x18\x01 \x01(\x05R\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\x02 \x01(\x05R\vmaxReplicas\x125\n" +
	"\x06target\x18\x03 \x01(\v2\x1d.graphpb.AutoscalingHpaTargetR\x06target\"_\n" +
	"\x14AutoscalingHpaTarget\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xf0\x01\n" +
	"\x14AutoscalingHpaStatus\x12)\n" +
	"\x10current_replicas\x18\x01 \x01(\x05R\x0fcurrentReplicas\x12)\n" +
	"\x10desired_replicas\x18\x02 \x01(\x05R\x0fdesiredReplicas\x12@\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2 .graphpb.AutoscalingHpaConditionR\n" +
	"conditions\x12@\n" +
	"\x0elas_scale_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\flasScaleTime\"\xc5\x01\n" +
	"\x17AutoscalingHpaCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12L\n" +
	"\x14last_transition_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastTransitionTime\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessageB3Z1github.com/cardinalhq/oteltools/pkg/graph/graphpbb\x06proto3"

var (
	file_autoscaling_hpa_proto_rawDescOnce sync.Once
	file_autoscaling_hpa_proto_rawDescData []byte
)

func file_autoscaling_hpa_proto_rawDescGZIP() []byte {
	file_autoscaling_hpa_proto_rawDescOnce.Do(func() {
		file_autoscaling_hpa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_autoscaling_hpa_proto_rawDesc), len(file_autoscaling_hpa_proto_rawDesc)))
	})
	return file_autoscaling_hpa_proto_rawDescData
}

var file_autoscaling_hpa_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_autoscaling_hpa_proto_goTypes = []any{
	(*AutoscalingHpaSummary)(nil),   // 0: graphpb.AutoscalingHpaSummary
	(*AutoscalingHpaSpec)(nil),      // 1: graphpb.AutoscalingHpaSpec
	(*AutoscalingHpaTarget)(nil),    // 2: graphpb.AutoscalingHpaTarget
	(*AutoscalingHpaStatus)(nil),    // 3: graphpb.AutoscalingHpaStatus
	(*AutoscalingHpaCondition)(nil), // 4: graphpb.AutoscalingHpaCondition
	(*BaseObject)(nil),              // 5: graphpb.BaseObject
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_autoscaling_hpa_proto_depIdxs = []int32{
	5, // 0: graphpb.AutoscalingHpaSummary.base_object:type_name -> graphpb.BaseObject
	1, // 1: graphpb.AutoscalingHpaSummary.spec:type_name -> graphpb.AutoscalingHpaSpec
	3, // 2: graphpb.AutoscalingHpaSummary.status:type_name -> graphpb.AutoscalingHpaStatus
	2, // 3: graphpb.AutoscalingHpaSpec.target:type_name -> graphpb.AutoscalingHpaTarget
	4, // 4: graphpb.AutoscalingHpaStatus.conditions:type_name -> graphpb.AutoscalingHpaCondition
	6, // 5: graphpb.AutoscalingHpaStatus.las_scale_time:type_name -> google.protobuf.Timestamp
	6, // 6: graphpb.AutoscalingHpaCondition.last_transition_time:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_autoscaling_hpa_proto_init() }
func file_autoscaling_hpa_proto_init() {
	if File_autoscaling_hpa_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_autoscaling_hpa_proto_rawDesc), len(file_autoscaling_hpa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_autoscaling_hpa_proto_goTypes,
		DependencyIndexes: file_autoscaling_hpa_proto_depIdxs,
		MessageInfos:      file_autoscaling_hpa_proto_msgTypes,
	}.Build()
	File_autoscaling_hpa_proto = out.File
	file_autoscaling_hpa_proto_goTypes = nil
	file_autoscaling_hpa_proto_depIdxs = nil
}
