// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: packaged_object.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PackagedObject represents an object with arbitrary attributes.
type PackagedObject struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourceAttributes map[string]string      `protobuf:"bytes,1,rep,name=resource_attributes,json=resourceAttributes,proto3" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RecordAttributes   map[string]string      `protobuf:"bytes,2,rep,name=record_attributes,json=recordAttributes,proto3" json:"record_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Object:
	//
	//	*PackagedObject_PodSummary
	//	*PackagedObject_SecretSummary
	//	*PackagedObject_ConfigMapSummary
	//	*PackagedObject_AppsDeploymentSummary
	//	*PackagedObject_AppsStatefulSetSummary
	//	*PackagedObject_AppsDaemonSetSummary
	//	*PackagedObject_AppsReplicaSetSummary
	//	*PackagedObject_AutoscalingHpaSummary
	Object        isPackagedObject_Object `protobuf_oneof:"object"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagedObject) Reset() {
	*x = PackagedObject{}
	mi := &file_packaged_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagedObject) ProtoMessage() {}

func (x *PackagedObject) ProtoReflect() protoreflect.Message {
	mi := &file_packaged_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagedObject.ProtoReflect.Descriptor instead.
func (*PackagedObject) Descriptor() ([]byte, []int) {
	return file_packaged_object_proto_rawDescGZIP(), []int{0}
}

func (x *PackagedObject) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

func (x *PackagedObject) GetRecordAttributes() map[string]string {
	if x != nil {
		return x.RecordAttributes
	}
	return nil
}

func (x *PackagedObject) GetObject() isPackagedObject_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PackagedObject) GetPodSummary() *PodSummary {
	if x != nil {
		if x, ok := x.Object.(*PackagedObject_PodSummary); ok {
			return x.PodSummary
		}
	}
	return nil
}

func (x *PackagedObject) GetSecretSummary() *SecretSummary {
	if x != nil {
		if x, ok := x.Object.(*PackagedObject_SecretSummary); ok {
			return x.SecretSummary
		}
	}
	return nil
}

func (x *PackagedObject) GetConfigMapSummary() *ConfigMapSummary {
	if x != nil {
		if x, ok := x.Object.(*PackagedObject_ConfigMapSummary); ok {
			return x.ConfigMapSummary
		}
	}
	return nil
}

func (x *PackagedObject) GetAppsDeploymentSummary() *AppsDeploymentSummary {
	if x != nil {
		if x, ok := x.Object.(*PackagedObject_AppsDeploymentSummary); ok {
			return x.AppsDeploymentSummary
		}
	}
	return nil
}

func (x *PackagedObject) GetAppsStatefulSetSummary() *AppsStatefulSetSummary {
	if x != nil {
		if x, ok := x.Object.(*PackagedObject_AppsStatefulSetSummary); ok {
			return x.AppsStatefulSetSummary
		}
	}
	return nil
}

func (x *PackagedObject) GetAppsDaemonSetSummary() *AppsDaemonSetSummary {
	if x != nil {
		if x, ok := x.Object.(*PackagedObject_AppsDaemonSetSummary); ok {
			return x.AppsDaemonSetSummary
		}
	}
	return nil
}

func (x *PackagedObject) GetAppsReplicaSetSummary() *AppsReplicaSetSummary {
	if x != nil {
		if x, ok := x.Object.(*PackagedObject_AppsReplicaSetSummary); ok {
			return x.AppsReplicaSetSummary
		}
	}
	return nil
}

func (x *PackagedObject) GetAutoscalingHpaSummary() *AutoscalingHpaSummary {
	if x != nil {
		if x, ok := x.Object.(*PackagedObject_AutoscalingHpaSummary); ok {
			return x.AutoscalingHpaSummary
		}
	}
	return nil
}

type isPackagedObject_Object interface {
	isPackagedObject_Object()
}

type PackagedObject_PodSummary struct {
	PodSummary *PodSummary `protobuf:"bytes,3,opt,name=pod_summary,json=podSummary,proto3,oneof"`
}

type PackagedObject_SecretSummary struct {
	SecretSummary *SecretSummary `protobuf:"bytes,4,opt,name=secret_summary,json=secretSummary,proto3,oneof"`
}

type PackagedObject_ConfigMapSummary struct {
	ConfigMapSummary *ConfigMapSummary `protobuf:"bytes,5,opt,name=config_map_summary,json=configMapSummary,proto3,oneof"`
}

type PackagedObject_AppsDeploymentSummary struct {
	AppsDeploymentSummary *AppsDeploymentSummary `protobuf:"bytes,6,opt,name=apps_deployment_summary,json=appsDeploymentSummary,proto3,oneof"`
}

type PackagedObject_AppsStatefulSetSummary struct {
	AppsStatefulSetSummary *AppsStatefulSetSummary `protobuf:"bytes,7,opt,name=apps_stateful_set_summary,json=appsStatefulSetSummary,proto3,oneof"`
}

type PackagedObject_AppsDaemonSetSummary struct {
	AppsDaemonSetSummary *AppsDaemonSetSummary `protobuf:"bytes,8,opt,name=apps_daemon_set_summary,json=appsDaemonSetSummary,proto3,oneof"`
}

type PackagedObject_AppsReplicaSetSummary struct {
	AppsReplicaSetSummary *AppsReplicaSetSummary `protobuf:"bytes,9,opt,name=apps_replica_set_summary,json=appsReplicaSetSummary,proto3,oneof"`
}

type PackagedObject_AutoscalingHpaSummary struct {
	AutoscalingHpaSummary *AutoscalingHpaSummary `protobuf:"bytes,10,opt,name=autoscaling_hpa_summary,json=autoscalingHpaSummary,proto3,oneof"`
}

func (*PackagedObject_PodSummary) isPackagedObject_Object() {}

func (*PackagedObject_SecretSummary) isPackagedObject_Object() {}

func (*PackagedObject_ConfigMapSummary) isPackagedObject_Object() {}

func (*PackagedObject_AppsDeploymentSummary) isPackagedObject_Object() {}

func (*PackagedObject_AppsStatefulSetSummary) isPackagedObject_Object() {}

func (*PackagedObject_AppsDaemonSetSummary) isPackagedObject_Object() {}

func (*PackagedObject_AppsReplicaSetSummary) isPackagedObject_Object() {}

func (*PackagedObject_AutoscalingHpaSummary) isPackagedObject_Object() {}

type PackagedObjectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PackagedObject      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagedObjectList) Reset() {
	*x = PackagedObjectList{}
	mi := &file_packaged_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagedObjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagedObjectList) ProtoMessage() {}

func (x *PackagedObjectList) ProtoReflect() protoreflect.Message {
	mi := &file_packaged_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagedObjectList.ProtoReflect.Descriptor instead.
func (*PackagedObjectList) Descriptor() ([]byte, []int) {
	return file_packaged_object_proto_rawDescGZIP(), []int{1}
}

func (x *PackagedObjectList) GetItems() []*PackagedObject {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_packaged_object_proto protoreflect.FileDescriptor

const file_packaged_object_proto_rawDesc = "" +
	"\n" +
	"\x15packaged_object.proto\x12\agraphpb\x1a\x14apps_daemonset.proto\x1a\x15apps_deployment.proto\x1a\x15apps_replicaset.proto\x1a\x16apps_statefulset.proto\x1a\x15autoscaling_hpa.proto\x1a\x0fconfigmap.proto\x1a\tpod.proto\x1a\fsecret.proto\"\xed\a\n" +
	"\x0ePackagedObject\x12`\n" +
	"\x13resource_attributes\x18\x01 \x03(\v2/.graphpb.PackagedObject.ResourceAttributesEntryR\x12resourceAttributes\x12Z\n" +
	"\x11record_attributes\x18\x02 \x03(\v2-.graphpb.PackagedObject.RecordAttributesEntryR\x10recordAttributes\x126\n" +
	"\vpod_summary\x18\x03 \x01(\v2\x13.graphpb.PodSummaryH\x00R\n" +
	"podSummary\x12?\n" +
	"\x0esecret_summary\x18\x04 \x01(\v2\x16.graphpb.SecretSummaryH\x00R\rsecretSummary\x12I\n" +
	"\x12config_map_summary\x18\x05 \x01(\v2\x19.graphpb.ConfigMapSummaryH\x00R\x10configMapSummary\x12X\n" +
	"\x17apps_deployment_summary\x18\x06 \x01(\v2\x1e.graphpb.AppsDeploymentSummaryH\x00R\x15appsDeploymentSummary\x12\\\n" +
	"\x19apps_stateful_set_summary\x18\a \x01(\v2\x1f.graphpb.AppsStatefulSetSummaryH\x00R\x16appsStatefulSetSummary\x12V\n" +
	"\x17apps_daemon_set_summary\x18\b \x01(\v2\x1d.graphpb.AppsDaemonSetSummaryH\x00R\x14appsDaemonSetSummary\x12Y\n" +
	"\x18apps_replica_set_summary\x18\t \x01(\v2\x1e.graphpb.AppsReplicaSetSummaryH\x00R\x15appsReplicaSetSummary\x12X\n" +
	"\x17autoscaling_hpa_summary\x18\n" +
	" \x01(\v2\x1e.graphpb.AutoscalingHpaSummaryH\x00R\x15autoscalingHpaSummary\x1aE\n" +
	"\x17ResourceAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15RecordAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06object\"C\n" +
	"\x12PackagedObjectList\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.graphpb.PackagedObjectR\x05itemsB3Z1github.com/cardinalhq/oteltools/pkg/graph/graphpbb\x06proto3"

var (
	file_packaged_object_proto_rawDescOnce sync.Once
	file_packaged_object_proto_rawDescData []byte
)

func file_packaged_object_proto_rawDescGZIP() []byte {
	file_packaged_object_proto_rawDescOnce.Do(func() {
		file_packaged_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packaged_object_proto_rawDesc), len(file_packaged_object_proto_rawDesc)))
	})
	return file_packaged_object_proto_rawDescData
}

var file_packaged_object_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packaged_object_proto_goTypes = []any{
	(*PackagedObject)(nil),         // 0: graphpb.PackagedObject
	(*PackagedObjectList)(nil),     // 1: graphpb.PackagedObjectList
	nil,                            // 2: graphpb.PackagedObject.ResourceAttributesEntry
	nil,                            // 3: graphpb.PackagedObject.RecordAttributesEntry
	(*PodSummary)(nil),             // 4: graphpb.PodSummary
	(*SecretSummary)(nil),          // 5: graphpb.SecretSummary
	(*ConfigMapSummary)(nil),       // 6: graphpb.ConfigMapSummary
	(*AppsDeploymentSummary)(nil),  // 7: graphpb.AppsDeploymentSummary
	(*AppsStatefulSetSummary)(nil), // 8: graphpb.AppsStatefulSetSummary
	(*AppsDaemonSetSummary)(nil),   // 9: graphpb.AppsDaemonSetSummary
	(*AppsReplicaSetSummary)(nil),  // 10: graphpb.AppsReplicaSetSummary
	(*AutoscalingHpaSummary)(nil),  // 11: graphpb.AutoscalingHpaSummary
}
var file_packaged_object_proto_depIdxs = []int32{
	2,  // 0: graphpb.PackagedObject.resource_attributes:type_name -> graphpb.PackagedObject.ResourceAttributesEntry
	3,  // 1: graphpb.PackagedObject.record_attributes:type_name -> graphpb.PackagedObject.RecordAttributesEntry
	4,  // 2: graphpb.PackagedObject.pod_summary:type_name -> graphpb.PodSummary
	5,  // 3: graphpb.PackagedObject.secret_summary:type_name -> graphpb.SecretSummary
	6,  // 4: graphpb.PackagedObject.config_map_summary:type_name -> graphpb.ConfigMapSummary
	7,  // 5: graphpb.PackagedObject.apps_deployment_summary:type_name -> graphpb.AppsDeploymentSummary
	8,  // 6: graphpb.PackagedObject.apps_stateful_set_summary:type_name -> graphpb.AppsStatefulSetSummary
	9,  // 7: graphpb.PackagedObject.apps_daemon_set_summary:type_name -> graphpb.AppsDaemonSetSummary
	10, // 8: graphpb.PackagedObject.apps_replica_set_summary:type_name -> graphpb.AppsReplicaSetSummary
	11, // 9: graphpb.PackagedObject.autoscaling_hpa_summary:type_name -> graphpb.AutoscalingHpaSummary
	0,  // 10: graphpb.PackagedObjectList.items:type_name -> graphpb.PackagedObject
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_packaged_object_proto_init() }
func file_packaged_object_proto_init() {
	if File_packaged_object_proto != nil {
		return
	}
	file_apps_daemonset_proto_init()
	file_apps_deployment_proto_init()
	file_apps_replicaset_proto_init()
	file_apps_statefulset_proto_init()
	file_autoscaling_hpa_proto_init()
	file_configmap_proto_init()
	file_pod_proto_init()
	file_secret_proto_init()
	file_packaged_object_proto_msgTypes[0].OneofWrappers = []any{
		(*PackagedObject_PodSummary)(nil),
		(*PackagedObject_SecretSummary)(nil),
		(*PackagedObject_ConfigMapSummary)(nil),
		(*PackagedObject_AppsDeploymentSummary)(nil),
		(*PackagedObject_AppsStatefulSetSummary)(nil),
		(*PackagedObject_AppsDaemonSetSummary)(nil),
		(*PackagedObject_AppsReplicaSetSummary)(nil),
		(*PackagedObject_AutoscalingHpaSummary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packaged_object_proto_rawDesc), len(file_packaged_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packaged_object_proto_goTypes,
		DependencyIndexes: file_packaged_object_proto_depIdxs,
		MessageInfos:      file_packaged_object_proto_msgTypes,
	}.Build()
	File_packaged_object_proto = out.File
	file_packaged_object_proto_goTypes = nil
	file_packaged_object_proto_depIdxs = nil
}
