// Copyright 2024-2025 CardinalHQ, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pod.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PodSummary summarizes a Kubernetes Pod.
type PodSummary struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BaseObject *BaseObject            `protobuf:"bytes,1,opt,name=base_object,json=baseObject,proto3" json:"base_object,omitempty"`
	// "spec" is the spec of the Pod, which is static.
	Spec *PodSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// "status" is the dynamic status of the Pod.
	Status        *PodStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSummary) Reset() {
	*x = PodSummary{}
	mi := &file_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSummary) ProtoMessage() {}

func (x *PodSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSummary.ProtoReflect.Descriptor instead.
func (*PodSummary) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{0}
}

func (x *PodSummary) GetBaseObject() *BaseObject {
	if x != nil {
		return x.BaseObject
	}
	return nil
}

func (x *PodSummary) GetSpec() *PodSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *PodSummary) GetStatus() *PodStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// PodSpec is the spec of a PodSummary.
type PodSpec struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Containers         []*PodContainerSpec    `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	ServiceAccountName string                 `protobuf:"bytes,2,opt,name=service_account_name,json=serviceAccountName,proto3" json:"service_account_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PodSpec) Reset() {
	*x = PodSpec{}
	mi := &file_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSpec) ProtoMessage() {}

func (x *PodSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSpec.ProtoReflect.Descriptor instead.
func (*PodSpec) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{1}
}

func (x *PodSpec) GetContainers() []*PodContainerSpec {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *PodSpec) GetServiceAccountName() string {
	if x != nil {
		return x.ServiceAccountName
	}
	return ""
}

// PodStatus is the status of a PodSummary.
type PodStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostIps         []string               `protobuf:"bytes,1,rep,name=host_ips,json=hostIps,proto3" json:"host_ips,omitempty"`
	PodIps          []string               `protobuf:"bytes,2,rep,name=pod_ips,json=podIps,proto3" json:"pod_ips,omitempty"`
	Phase           string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	PhaseMessage    string                 `protobuf:"bytes,5,opt,name=phase_message,json=phaseMessage,proto3" json:"phase_message,omitempty"`
	ContainerStatus []*PodContainerStatus  `protobuf:"bytes,6,rep,name=container_status,json=containerStatus,proto3" json:"container_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PodStatus) Reset() {
	*x = PodStatus{}
	mi := &file_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatus) ProtoMessage() {}

func (x *PodStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatus.ProtoReflect.Descriptor instead.
func (*PodStatus) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{2}
}

func (x *PodStatus) GetHostIps() []string {
	if x != nil {
		return x.HostIps
	}
	return nil
}

func (x *PodStatus) GetPodIps() []string {
	if x != nil {
		return x.PodIps
	}
	return nil
}

func (x *PodStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PodStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PodStatus) GetPhaseMessage() string {
	if x != nil {
		return x.PhaseMessage
	}
	return ""
}

func (x *PodStatus) GetContainerStatus() []*PodContainerStatus {
	if x != nil {
		return x.ContainerStatus
	}
	return nil
}

// PodContainerSummary summarizes a container within a Pod.
type PodContainerSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *PodContainerSpec      `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodContainerSummary) Reset() {
	*x = PodContainerSummary{}
	mi := &file_pod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodContainerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodContainerSummary) ProtoMessage() {}

func (x *PodContainerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodContainerSummary.ProtoReflect.Descriptor instead.
func (*PodContainerSummary) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{3}
}

func (x *PodContainerSummary) GetSpec() *PodContainerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// PodContainerSpec is the spec of a PodContainerSummary.
type PodContainerSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Resources      map[string]string      `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigMapNames []string               `protobuf:"bytes,4,rep,name=config_map_names,json=configMapNames,proto3" json:"config_map_names,omitempty"`
	SecretNames    []string               `protobuf:"bytes,5,rep,name=secret_names,json=secretNames,proto3" json:"secret_names,omitempty"`
	Ports          []*ContainerPortSpec   `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PodContainerSpec) Reset() {
	*x = PodContainerSpec{}
	mi := &file_pod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodContainerSpec) ProtoMessage() {}

func (x *PodContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodContainerSpec.ProtoReflect.Descriptor instead.
func (*PodContainerSpec) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{4}
}

func (x *PodContainerSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PodContainerSpec) GetResources() map[string]string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *PodContainerSpec) GetConfigMapNames() []string {
	if x != nil {
		return x.ConfigMapNames
	}
	return nil
}

func (x *PodContainerSpec) GetSecretNames() []string {
	if x != nil {
		return x.SecretNames
	}
	return nil
}

func (x *PodContainerSpec) GetPorts() []*ContainerPortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

// PodContainerStatus is the status of a PodContainerSummary.
type PodContainerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ready bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	// The "resources" field corresponds to the container resource requests.
	IsImagePullBackOff bool          `protobuf:"varint,3,opt,name=is_image_pull_back_off,json=isImagePullBackOff,proto3" json:"is_image_pull_back_off,omitempty"`
	IsCrashLoopBackOff bool          `protobuf:"varint,4,opt,name=is_crash_loop_back_off,json=isCrashLoopBackOff,proto3" json:"is_crash_loop_back_off,omitempty"`
	WasOomKilled       bool          `protobuf:"varint,5,opt,name=was_oom_killed,json=wasOomKilled,proto3" json:"was_oom_killed,omitempty"`
	Image              *ImageSummary `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PodContainerStatus) Reset() {
	*x = PodContainerStatus{}
	mi := &file_pod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodContainerStatus) ProtoMessage() {}

func (x *PodContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodContainerStatus.ProtoReflect.Descriptor instead.
func (*PodContainerStatus) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{5}
}

func (x *PodContainerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodContainerStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *PodContainerStatus) GetIsImagePullBackOff() bool {
	if x != nil {
		return x.IsImagePullBackOff
	}
	return false
}

func (x *PodContainerStatus) GetIsCrashLoopBackOff() bool {
	if x != nil {
		return x.IsCrashLoopBackOff
	}
	return false
}

func (x *PodContainerStatus) GetWasOomKilled() bool {
	if x != nil {
		return x.WasOomKilled
	}
	return false
}

func (x *PodContainerStatus) GetImage() *ImageSummary {
	if x != nil {
		return x.Image
	}
	return nil
}

// ContainerPortSpec is the spec of a container port.
type ContainerPortSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort int32                  `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPortSpec) Reset() {
	*x = ContainerPortSpec{}
	mi := &file_pod_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPortSpec) ProtoMessage() {}

func (x *ContainerPortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPortSpec.ProtoReflect.Descriptor instead.
func (*ContainerPortSpec) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerPortSpec) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *ContainerPortSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerPortSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

var File_pod_proto protoreflect.FileDescriptor

const file_pod_proto_rawDesc = "" +
	"\n" +
	"\tpod.proto\x12\agraphpb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"base.proto\x1a\vimage.proto\"\x94\x01\n" +
	"\n" +
	"PodSummary\x124\n" +
	"\vbase_object\x18\x01 \x01(\v2\x13.graphpb.BaseObjectR\n" +
	"baseObject\x12$\n" +
	"\x04spec\x18\x02 \x01(\v2\x10.graphpb.PodSpecR\x04spec\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.graphpb.PodStatusR\x06status\"v\n" +
	"\aPodSpec\x129\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x19.graphpb.PodContainerSpecR\n" +
	"containers\x120\n" +
	"\x14service_account_name\x18\x02 \x01(\tR\x12serviceAccountName\"\xfd\x01\n" +
	"\tPodStatus\x12\x19\n" +
	"\bhost_ips\x18\x01 \x03(\tR\ahostIps\x12\x17\n" +
	"\apod_ips\x18\x02 \x03(\tR\x06podIps\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12#\n" +
	"\rphase_message\x18\x05 \x01(\tR\fphaseMessage\x12F\n" +
	"\x10container_status\x18\x06 \x03(\v2\x1b.graphpb.PodContainerStatusR\x0fcontainerStatus\"D\n" +
	"\x13PodContainerSummary\x12-\n" +
	"\x04spec\x18\x01 \x01(\v2\x19.graphpb.PodContainerSpecR\x04spec\"\xc1\x02\n" +
	"\x10PodContainerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12F\n" +
	"\tresources\x18\x03 \x03(\v2(.graphpb.PodContainerSpec.ResourcesEntryR\tresources\x12(\n" +
	"\x10config_map_names\x18\x04 \x03(\tR\x0econfigMapNames\x12!\n" +
	"\fsecret_names\x18\x05 \x03(\tR\vsecretNames\x120\n" +
	"\x05ports\x18\x06 \x03(\v2\x1a.graphpb.ContainerPortSpecR\x05ports\x1a<\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x12PodContainerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x122\n" +
	"\x16is_image_pull_back_off\x18\x03 \x01(\bR\x12isImagePullBackOff\x122\n" +
	"\x16is_crash_loop_back_off\x18\x04 \x01(\bR\x12isCrashLoopBackOff\x12$\n" +
	"\x0ewas_oom_killed\x18\x05 \x01(\bR\fwasOomKilled\x12+\n" +
	"\x05image\x18\x06 \x01(\v2\x15.graphpb.ImageSummaryR\x05image\"j\n" +
	"\x11ContainerPortSpec\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\rcontainerPort\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocolB3Z1github.com/cardinalhq/oteltools/pkg/graph/graphpbb\x06proto3"

var (
	file_pod_proto_rawDescOnce sync.Once
	file_pod_proto_rawDescData []byte
)

func file_pod_proto_rawDescGZIP() []byte {
	file_pod_proto_rawDescOnce.Do(func() {
		file_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pod_proto_rawDesc), len(file_pod_proto_rawDesc)))
	})
	return file_pod_proto_rawDescData
}

var file_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pod_proto_goTypes = []any{
	(*PodSummary)(nil),            // 0: graphpb.PodSummary
	(*PodSpec)(nil),               // 1: graphpb.PodSpec
	(*PodStatus)(nil),             // 2: graphpb.PodStatus
	(*PodContainerSummary)(nil),   // 3: graphpb.PodContainerSummary
	(*PodContainerSpec)(nil),      // 4: graphpb.PodContainerSpec
	(*PodContainerStatus)(nil),    // 5: graphpb.PodContainerStatus
	(*ContainerPortSpec)(nil),     // 6: graphpb.ContainerPortSpec
	nil,                           // 7: graphpb.PodContainerSpec.ResourcesEntry
	(*BaseObject)(nil),            // 8: graphpb.BaseObject
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*ImageSummary)(nil),          // 10: graphpb.ImageSummary
}
var file_pod_proto_depIdxs = []int32{
	8,  // 0: graphpb.PodSummary.base_object:type_name -> graphpb.BaseObject
	1,  // 1: graphpb.PodSummary.spec:type_name -> graphpb.PodSpec
	2,  // 2: graphpb.PodSummary.status:type_name -> graphpb.PodStatus
	4,  // 3: graphpb.PodSpec.containers:type_name -> graphpb.PodContainerSpec
	9,  // 4: graphpb.PodStatus.started_at:type_name -> google.protobuf.Timestamp
	5,  // 5: graphpb.PodStatus.container_status:type_name -> graphpb.PodContainerStatus
	4,  // 6: graphpb.PodContainerSummary.spec:type_name -> graphpb.PodContainerSpec
	7,  // 7: graphpb.PodContainerSpec.resources:type_name -> graphpb.PodContainerSpec.ResourcesEntry
	6,  // 8: graphpb.PodContainerSpec.ports:type_name -> graphpb.ContainerPortSpec
	10, // 9: graphpb.PodContainerStatus.image:type_name -> graphpb.ImageSummary
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pod_proto_init() }
func file_pod_proto_init() {
	if File_pod_proto != nil {
		return
	}
	file_base_proto_init()
	file_image_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pod_proto_rawDesc), len(file_pod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pod_proto_goTypes,
		DependencyIndexes: file_pod_proto_depIdxs,
		MessageInfos:      file_pod_proto_msgTypes,
	}.Build()
	File_pod_proto = out.File
	file_pod_proto_goTypes = nil
	file_pod_proto_depIdxs = nil
}
